kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: kube-basic
data:
  key: |
    server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://sample-web:8080;
      }
    }